# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gym_diplomacy.envs import proto_message_pb2 as gym__diplomacy_dot_envs_dot_proto__message__pb2


class DiplomacyGymServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAction = channel.unary_unary(
        '/dip_q.DiplomacyGymService/GetAction',
        request_serializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.BandanaRequest.SerializeToString,
        response_deserializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.DiplomacyGymResponse.FromString,
        )
    self.GetStrategyAction = channel.unary_unary(
        '/dip_q.DiplomacyGymService/GetStrategyAction',
        request_serializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.BandanaRequest.SerializeToString,
        response_deserializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.DiplomacyGymOrdersResponse.FromString,
        )


class DiplomacyGymServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStrategyAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiplomacyGymServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAction': grpc.unary_unary_rpc_method_handler(
          servicer.GetAction,
          request_deserializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.BandanaRequest.FromString,
          response_serializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.DiplomacyGymResponse.SerializeToString,
      ),
      'GetStrategyAction': grpc.unary_unary_rpc_method_handler(
          servicer.GetStrategyAction,
          request_deserializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.BandanaRequest.FromString,
          response_serializer=gym__diplomacy_dot_envs_dot_proto__message__pb2.DiplomacyGymOrdersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dip_q.DiplomacyGymService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
